# Automatically triggered on PR
# No CI triggers on branches
pr:
  autoCancel: true
  branches:
    exclude:
      - main
  paths:
    include:
      - 'azure-devops/*'

trigger: none

parameters:
  - name: 'AZURERM_PROVIDER_CUSTOM_VERSION'
    displayName: 'Azure provider version to download a custom provider. Use "none" to skip custom provider.'
    type: string
    default: 'none'
  - name: 'AZURERM_PROVIDER_CUSTOM_RELEASE'
    displayName: 'Azure provider release to download a custom provider. Use "none" to skip custom provider.'
    type: string
    default: 'none'

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: pagopaCommons
      type: github
      name: pagopa/azure-pipeline-templates
      ref: refs/tags/v14
      endpoint: 'io-azure-devops-github-ro'

jobs:
  - job: terraform_checks
    steps:
      # 1. Install terraform and terragrunt
      - template: templates/terraform-setup/template.yaml@pagopaCommons
      # 2. Install custom provider
      - template: templates/terraform-custom-azurerm/template.yaml@pagopaCommons
        parameters:
          AZURERM_PROVIDER_CUSTOM_VERSION: '${{ parameters.AZURERM_PROVIDER_CUSTOM_VERSION }}'
          AZURERM_PROVIDER_CUSTOM_RELEASE: '${{ parameters.AZURERM_PROVIDER_CUSTOM_RELEASE }}'
      # 3. Install precommit
      - displayName: 'precommit checks'
        failOnStandardError: false
        script: |
          # wget https://raw.githubusercontent.com/pagopa/pre-commit-terraform/master/Dockerfile
          # docker build -t pre-commit .

          TERRAFORM_VERSION="$(cat .terraform-version)"
          echo $ACR_PASSWORD | docker login commoncacr.azurecr.io --username $ACR_USER --password-stdin

          base_dir=$(pwd)
          main_files=$(find . -name "project.tf")

          for item in ${main_files}
          do
            cd ${base_dir}
            # get working dir ... where to run the apply.
            wdir=$(dirname $item)
            echo $wdir

            cd $wdir
            rm .terraform.lock.hcl
            terraform init

            docker run -v $(pwd):/lint -w /lint/$wdir commoncacr.azurecr.io/pre-commit-terraform:$TERRAFORM_VERSION run -a
          done
